# Build a Docker Image of the Application and Push to GitHub Package Registry and a release is created and published
# This workflow is triggered on create of a new release. New releases are manually created by the developer – by design.
name: Build & Release Docker Image
on:
  release:
    types: [published]

  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: abscms

jobs:
  build:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Get Branch Names
        id: branch-name
        uses: tj-actions/branch-names@v4
        with:
          strip_tag_prefix: 'v'

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login To GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:latest
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ steps.branch-name.outputs.tag }}
